name: CI

# Ce workflow se déclenche sur les push vers la branche main et sur les pull requests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuration de Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Lint du code
      - name: Lint code with flake8
        run: flake8 .

      # 5. Étape de construction (vérification de compilation)
      - name: Build (compilation check)
        run: python -m compileall .

      # 6. Exécution des tests unitaires
      - name: Run tests with pytest
        run: pytest tests
